### ISSUE TITLE
Fails to build with system wlroots 0.15.0

### ISSUE THREAD

**Issue by jbeich** [Plagman/gamescope#316]
Regressed by [wlroots@1d3dd7f](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/1d3dd7fc08f2)
```c++
$ meson setup --force-fallback-for=libliftoff /tmp/gamescope_build
$ meson compile -C /tmp/gamescope_build
[...]
src/wlserver.cpp:26:10: fatal error: 'wlr/backend/noop.h' file not found
#include <wlr/backend/noop.h>
         ^~~~~~~~~~~~~~~~~~~~
```
See also:
- [sway fix](https://github.com/swaywm/sway/commit/0cd8efe0bb66)
- [downstream workaround](https://github.com/freebsd/freebsd-ports/blob/633b51aa6f3e/x11-wm/gamescope/files/patch-wlroots-0.15)

**Comment by emersion** [comment]
That's expected, only the subproject git submodule is supported. I'll bump it once wlroots 0.15.0 is released, but we might need some unreleased wlroots changes again at some point, and then 0.15.0 would stop working.

**Comment by jbeich** [comment]
See also:
https://github.com/swaywm/sway/commit/0cd8efe0bb66
https://github.com/freebsd/freebsd-ports/blob/main/x11-wm/gamescope/files/patch-wlroots-0.15

**Comment by emersion** [comment]
Done in 11f89c1b15eb8cf30cacfef42b092ef11808babb.

**Comment by jbeich** [comment]
Still fails here:
```c++
../src/wlserver.cpp:26:10: fatal error: 'wlr/backend/noop.h' file not found
#include <wlr/backend/noop.h>
         ^~~~~~~~~~~~~~~~~~~~
```

**Comment by jbeich** [comment]
I'm actually puzzled how 11f89c1 managed to pass CI. Did it bootleg noop.h from somewhere else?

**Comment by emersion** [comment]
Right, we install wlroots system-wide as a cheap way to bring all of its deps. Maybe we should explicitly install the deps instead.

Anyway, fixed in c1958be1d94d.
