### PR TITLE
Unbreak build with system wlroots 0.13.0

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by b380f3fbf24e. Both gamescope and wlroots define `generate_cvt_mode`.
```
$ meson setup --force-fallback-for=libliftoff /tmp/gamescope_build
$ meson compile -C /tmp/gamescope_build
[...]
src/cvt.cpp:23:10: fatal error: 'backend/drm/cvt.h' file not found
#include "backend/drm/cvt.h"
          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

### CODE REVIEW

**Review by emersion — APPROVED** [review]
Good catch, thanks!
