### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [Plagman/gamescope#140]
Regressed by ceeef3567d90 (part of #135). From [error log](https://github.com/Plagman/gamescope/files/5678996/gamescope-3.7.1.5.log):
```c++
src/steamcompmgr.cpp:857:28: error: variable-sized object may not be initialized
        uint32_t cursorDataBuffer[m_width * m_height] = {0};
                                  ^~~~~~~~~~~~~~~~~~
```

**Comment by emersion** [comment]
Can you try https://github.com/Plagman/gamescope/pull/141?

**Comment by jbeich** [comment]
It does help. I can't reproduce after applying #141.
