### ISSUE TITLE
3.11.11 fails to build on 32-bit systems

### ISSUE THREAD

**Issue by jbeich** [Plagman/gamescope#410]
Regressed by f1567634584f. From [error log](https://github.com/Plagman/gamescope/files/8054429/gamescope-3.11.11.log):
```c++
src/vblankmanager.cpp:285:18: error: no matching function for call to 'max'
                                sleepyTime = std::max( sleepyTime, 0l );
                                             ^~~~~~~~
/usr/include/c++/v1/algorithm:2633:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long long' vs. 'long')
max(const _Tp& __a, const _Tp& __b)
^
/usr/include/c++/v1/algorithm:2644:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'long long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/usr/include/c++/v1/algorithm:2653:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
/usr/include/c++/v1/algorithm:2624:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
```
Replacing `0l` with `0ll` helps but breaks 64-bit systems instead. Maybe it should use `std::max<int64_t>(...)`, `static_cast<int64_t>(0)` or similar where `int64_t` can probably be replaced by `decltype(sleepyTime)`.

**Comment by jbeich** [comment]
Fixed by 1594e02c84a7.
